//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorSenhasWeb.WSPasswordGenerator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://generator.password.com.br/", ConfigurationName="WSPasswordGenerator.PasswordGenerator")]
    public interface PasswordGenerator {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeradorSenhasWeb.WSPasswordGenerator.getPasswordsResponse getPasswords(GeradorSenhasWeb.WSPasswordGenerator.getPasswordsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPasswords", WrapperNamespace="http://generator.password.com.br/", IsWrapped=true)]
    public partial class getPasswordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string characters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int minSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int maxSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int numberOfPasswords;
        
        public getPasswordsRequest() {
        }
        
        public getPasswordsRequest(string characters, int minSize, int maxSize, int numberOfPasswords) {
            this.characters = characters;
            this.minSize = minSize;
            this.maxSize = maxSize;
            this.numberOfPasswords = numberOfPasswords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPasswordsResponse", WrapperNamespace="http://generator.password.com.br/", IsWrapped=true)]
    public partial class getPasswordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getPasswordsResponse() {
        }
        
        public getPasswordsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PasswordGeneratorChannel : GeradorSenhasWeb.WSPasswordGenerator.PasswordGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PasswordGeneratorClient : System.ServiceModel.ClientBase<GeradorSenhasWeb.WSPasswordGenerator.PasswordGenerator>, GeradorSenhasWeb.WSPasswordGenerator.PasswordGenerator {
        
        public PasswordGeneratorClient() {
        }
        
        public PasswordGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PasswordGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeradorSenhasWeb.WSPasswordGenerator.getPasswordsResponse GeradorSenhasWeb.WSPasswordGenerator.PasswordGenerator.getPasswords(GeradorSenhasWeb.WSPasswordGenerator.getPasswordsRequest request) {
            return base.Channel.getPasswords(request);
        }
        
        public string[] getPasswords(string characters, int minSize, int maxSize, int numberOfPasswords) {
            GeradorSenhasWeb.WSPasswordGenerator.getPasswordsRequest inValue = new GeradorSenhasWeb.WSPasswordGenerator.getPasswordsRequest();
            inValue.characters = characters;
            inValue.minSize = minSize;
            inValue.maxSize = maxSize;
            inValue.numberOfPasswords = numberOfPasswords;
            GeradorSenhasWeb.WSPasswordGenerator.getPasswordsResponse retVal = ((GeradorSenhasWeb.WSPasswordGenerator.PasswordGenerator)(this)).getPasswords(inValue);
            return retVal.@return;
        }
    }
}
